################################################################################
# NAME:		    makefile
#
# AUTHOR:	    Ethan D. Twardy
#
# DESCRIPTION:	    Makefile for the neural-network.tex file.
#
# CREATED:	    08/02/2017
#
# LAST EDITED:	    08/02/2017
###

neural-network:
